package com.snakeladders.model;

import java.util.Random;

public class ChanceField extends Field{
    /**
    Model class for the field that contains all the things that make up our implementation of Stigespillet

    Contents:

    All fields are generated by the GameScreenController Class. This class makes sure that you wo't be telwported ad infinitum.
    This class does nothing, aside from contributing to represent the state of the game.
    **/

    private int id;
    private enum Type {KEEPCARD, NEWTURN, DOUBLE, START, BACKWARDS} // Class within me
    private Type fieldtype;
    private Field teleportToField; //Used by ladderFields and occasionally chancefields, normally null for Normalfield.
    private Board board; // Reference to the board the field belongs to.
    
    public ChanceField(Board board, int i, Field teleportToField, Type type) {
        super(board,i,teleportToField);
//        this.fieldtype = Random.choice(Type); // Choose a type randomly.
    }
    public Type getFieldType(){ return this.fieldtype; }
}