package com.snakeladders.model;

public class LadderField extends Field{
    /**
    Model class for the field that contains all the things that make up our implementation of Stigespillet

    Contents:

    All fields are generated by the GameScreenController Class. This class makes sure that you wo't be telwported ad infinitum.
    This class does nothing, aside from contributing to represent the state of the game.

    private int id;
    private Field teleportToField; //Used by ladderFields and occasionally chancefields, normally null for Normalfield.
    private Board board; // Reference to the board the field belongs to.
    **/
    
    public LadderField(Board board, int i, Field teleportToField) {
        super(board,i,teleportToField);
    }
}