package com.snakeladders.model;

public class LadderField extends Field{
    /**
    Model class for the field that contains all the things that make up our implementation of Stigespillet

    Content:

    All fields are generated by the GameScreenController Class. This class makes sure that you wo't be teleported ad infinitum.
    This class does nothing, aside from contributing to represent the state of the game.

    private int id;
    private Board board; // Reference to the board the field belongs to.
    **/

    private Field teleportToField; //Used by ladderFields and occasionally chanceFields, normally null for normalField.

    public LadderField(int i, Field teleportToField, float x, float y, float size) { //Note that x and y are floats to the corresponding fieldActor
        super(i, x, y, size);
        if (teleportToField != null) {
            this.teleportToField = teleportToField;
        }

    }

    public Field getTeleportToField() {return this.teleportToField; }
    public void setTeleportToField(Field f) { this.teleportToField = f; }
}